Repository kubev2v/migration-planner, pull requests merged in 2025-10, with the labels that each got.

#596 ECOPROJECT-3329 | feat: Add static IP support
  api/v1alpha1/openapi.yaml
  api/v1alpha1/spec.gen.go
  api/v1alpha1/types.gen.go
  data/ignition.template
  internal/handlers/v1alpha1/mappers/inbound.go
  internal/handlers/validator/custom.go
  internal/handlers/validator/rules.go
  internal/image/builder.go
  internal/service/mappers/inbound.go
  internal/store/model/image.go
  pkg/migrations/sql/20250926140958_add_ipaddress_to_infra.sql
Labels: lgtm, approved

#621 ECOPROJECT-3341 | feat: Script to modify ISO password
  hack/change-ova-password.sh
Labels: approved

#622 cherry-pick: ECOPROJECT-3329 | feat: Add static IP support
  api/v1alpha1/openapi.yaml
  api/v1alpha1/spec.gen.go
  api/v1alpha1/types.gen.go
  data/ignition.template
  internal/handlers/v1alpha1/mappers/inbound.go
  internal/handlers/validator/custom.go
  internal/handlers/validator/rules.go
  internal/image/builder.go
  internal/service/mappers/inbound.go
  internal/store/model/image.go
  pkg/migrations/sql/20250926140958_add_ipaddress_to_infra.sql
Labels: lgtm

#628 NO-JIRA | ci: Add tekton file for building images from release_0.1.4-1 branch
  .tekton/migration-planner-agent-branch-push.yaml
  .tekton/migration-planner-api-branch-push.yaml
Labels: approved

#631 ECOPROJECT-3343 | fix: Support upgrade from prod to current main
  pkg/migrations/sql/20250730124058_update_assessment_table.sql
  pkg/migrations/sql/20250901090447_add_username_to_assessment.sql
  pkg/migrations/sql/20250923095242_add_owner_fields_to_assessment.sql
  pkg/migrations/sql/20251002131125_union_migrations.sql
Labels: lgtm, approved

#616 ECOPROJECT-3287 | feat: Write an script in ignition that will enable the bundled container
  Makefile
  data/ignition.template
  deploy/e2e.mk
  deploy/templates/service-template.yml
  internal/cli/generate.go
  internal/image/builder.go
Labels: lgtm, approved
