Repository kubev2v/migration-planner, pull requests merged in 2025-09, with the labels that each got.

#523 ECOPROJECT-3266 | feat: RVools - Transform vendor names to expected format
  internal/agent/collector/vsphere.go
  internal/rvtools/datastores.go
Labels: lgtm

#531 ECOPROJECT-3252 | feat: unit test coverage of rvtools parser
  internal/rvtools/parser.go
  internal/rvtools/parser_test.go
  internal/rvtools/rvtools_suite_test.go
Labels: lgtm

#534 ECOPROJECT-3221 | feat: Migrate the example source to assessment
  api/v1alpha1/openapi.yaml
  api/v1alpha1/spec.gen.go
  api/v1alpha1/types.gen.go
  internal/api/client/client.gen.go
  internal/api/server/server.gen.go
  internal/cli/get.go
  internal/handlers/v1alpha1/assessment.go
  internal/handlers/v1alpha1/assessment_test.go
  internal/handlers/v1alpha1/source.go
  internal/service/assessment.go
  internal/service/assessment_test.go
  internal/service/source.go
  internal/service/source_test.go
  internal/store/assessment_test.go
  internal/store/options.go
  internal/store/store.go
  internal/store/store_test.go
Labels: lgtm

#560 NO-JIRA | feat: Add Envoy request ID extension to backend agent API
  deploy/templates/service-template.yml
Labels: lgtm

#542 NO-JIRA | refactor: e2e - separate the interfaces of the migration planner to small interfaces and create test wrappers
  test/e2e/agent/agent.go
  test/e2e/agent/agent_api.go
  test/e2e/agent/agent_helpers.go
  test/e2e/e2e_disconnected_env_test.go
  test/e2e/e2e_global_vars.go
  test/e2e/e2e_multiple_users_test.go
  test/e2e/e2e_suite_test.go
  test/e2e/e2e_test.go
  test/e2e/helpers/test_helpers.go
  test/e2e/model/e2e_models.go
  test/e2e/service/interfaces.go
  test/e2e/service/service.go
  test/e2e/service/service_api.go
  test/e2e/utils/auth.go
  test/e2e/utils/command.go
  test/e2e/utils/file.go
  test/e2e/utils/log.go
Labels: need-second-approve

#570 ECOPROJECT-3202 | build: Adding local stack with staging data
  .gitignore
  hack/staging-debug-tool/.env-debug.example
  hack/staging-debug-tool/README.md
  hack/staging-debug-tool/auth_local/Dockerfile.ui-local
  hack/staging-debug-tool/auth_local/authFetch.ts
  hack/staging-debug-tool/auth_local/debug-compose-local-file.yaml
  hack/staging-debug-tool/auth_local/set-ui-token.html
  hack/staging-debug-tool/auth_none/Dockerfile.ui
  hack/staging-debug-tool/auth_none/debug-compose.yaml
  hack/staging-debug-tool/debug-with-staging-complete.sh
  hack/staging-debug-tool/generate-user-tokens.sh
  hack/staging-debug-tool/load-data.sh
  hack/staging-debug-tool/restart-api.sh
  hack/staging-debug-tool/sync-staging-via-gabi.sh
  hack/staging-debug-tool/test-gabi-response.sh
Labels: lgtm, approved

#548 NO-JIRA | Add doc for install cluster using AI and do the migration
  doc/phase2/install-new-cluster.md
  doc/phase2/migrate-vms.md
Labels: lgtm, approved
